version: '3'
services:
  mongo:
    container_name: mongo
    image: 'mongo'
    restart: always
    ports:
      - '27017:27017'
  explorer-app:
    container_name: explorer-app
    image: 462619610638.dkr.ecr.eu-west-1.amazonaws.com/smilo/explorer:testnet
    command: ./app.js
    restart: always
    environment:
      MONGO_URI: 'mongodb://mongo/explorerDB'
    ports:
      - '3000:3000'
    depends_on:
      - mongo
    volumes:
      - ./config.json:/app/config.json
  explorer-sync:
    container_name: explorer-sync
    image: 462619610638.dkr.ecr.eu-west-1.amazonaws.com/smilo/explorer:testnet
    command: ./tools/sync.js
    restart: always
    environment:
      MONGO_URI: 'mongodb://mongo/explorerDB'
    depends_on:
      - mongo
    volumes:
      - ./config.json:/app/config.json
  explorer-stats:
    container_name: explorer-stats
    image: 462619610638.dkr.ecr.eu-west-1.amazonaws.com/smilo/explorer:testnet
    command: ./tools/stats.js
    restart: always
    environment:
      MONGO_URI: 'mongodb://mongo/explorerDB'
    depends_on:
      - mongo
    volumes:
      - ./config.json:/app/config.json
  explorer-richlist:
    container_name: explorer-richlist
    image: 462619610638.dkr.ecr.eu-west-1.amazonaws.com/smilo/explorer:testnet
    command: ./tools/richlist.js
    restart: always
    environment:
      MONGO_URI: 'mongodb://mongo/explorerDB'
    depends_on:
      - mongo
    volumes:
      - ./config.json:/app/config.json